
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imedia24test?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081

flickr:
  apiKey: 6aad027db7465a7da0f46af143861351
  apiSecret: d1bb221efd9478b2
  appKey: 72157719641963559-0099cd38f7a6eee4
  appSecret: 8d030740f9cd580f




